import type { IconProps } from "@tabler/icons-react";
import {
  IconHome,
  IconSearch,
  IconMenu2,
  IconChevronRight,
  IconChevronDown,
  IconChevronLeft,
  IconChevronUp,
  IconArrowRight,
  IconPlus,
  IconTrash,
  IconEdit,
  IconX,
  IconCheck,
  IconCopy,
  IconRefresh,
  IconDownload,
  IconShoppingCart,
  IconPackage,
  IconCreditCard,
  IconWallet,
  IconGift,
  IconTag,
  IconTruck,
  IconHeart,
  IconUser,
  IconBell,
  IconLock,
  IconMail,
  IconLogout,
  IconEye,
  IconEyeOff,
  IconCamera,
  IconPhoto,
  IconPlayerPlay,
  IconPlayerPause,
  IconPhone,
  IconMessageCircle,
  IconShare,
  IconInfoCircle,
  IconAlertCircle,
  IconStar,
  IconSettings,
  IconMinus,
  IconBookmark,
  IconCalendar,
  IconClock,
  IconFilter,
  IconUpload,
  IconFolder,
  IconFileText,
  IconLink,
  IconExternalLink,
  IconWorld,
  IconMapPin,
  IconBuilding,
  IconBriefcase,
  IconUsers,
  IconUserPlus,
  IconShield,
  IconShieldCheck,
  IconKey,
  IconWifi,
  IconDatabase,
  IconServer,
  IconCloud,
  IconPrinter,
  IconQrcode,
  IconBarcode,
  IconClipboard,
  IconClipboardCheck,
  IconHistory,
  IconBolt,
  IconFlag,
  IconThumbUp,
  IconThumbDown,
  IconSun,
  IconMoon,
  IconLayoutGrid,
  IconList,
  IconChartBar,
  IconChartPie,
  IconTrendingUp,
  IconArrowLeft,
  IconArrowsSort,
  // Solid ("Filled") counterparts — used when <Icon solid /> is set
  IconSearchFilled,
  IconMenu2Filled,
  IconChevronRightFilled,
  IconTrashFilled,
  IconEditFilled,
  IconXFilled,
  IconCopyFilled,
  IconDownloadFilled,
  IconShoppingCartFilled,
  IconCreditCardFilled,
  IconGiftFilled,
  IconTagFilled,
  IconTruckFilled,
  IconHeartFilled,
  IconUserFilled,
  IconBellFilled,
  IconLockFilled,
  IconMailFilled,
  IconEyeFilled,
  IconCameraFilled,
  IconPhotoFilled,
  IconPlayerPlayFilled,
  IconPlayerPauseFilled,
  IconPhoneFilled,
  IconMessageCircleFilled,
  IconInfoCircleFilled,
  IconAlertCircleFilled,
  IconStarFilled,
  IconSettingsFilled,
  IconBookmarkFilled,
  IconCalendarFilled,
  IconClockFilled,
  IconFilterFilled,
  IconFolderFilled,
  IconFileTextFilled,
  IconLinkFilled,
  IconExternalLinkFilled,
  IconWorldFilled,
  IconMapPinFilled,
  IconBriefcaseFilled,
  IconShieldFilled,
  IconShieldCheckFilled,
  IconKeyFilled,
  IconDatabaseFilled,
  IconCloudFilled,
  IconClipboardFilled,
  IconClipboardCheckFilled,
  IconBoltFilled,
  IconFlagFilled,
  IconThumbUpFilled,
  IconThumbDownFilled,
  IconSunFilled,
  IconMoonFilled,
  IconLayoutGridFilled,
  IconListFilled,
  IconChartPieFilled,
  IconHomeFilled,
} from "@tabler/icons-react";

export const icons = {
  // Navigation
  home: IconHome,
  search: IconSearch,
  menu: IconMenu2,
  chevronRight: IconChevronRight,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronUp: IconChevronUp,
  arrowRight: IconArrowRight,

  // Actions
  plus: IconPlus,
  trash: IconTrash,
  edit: IconEdit,
  close: IconX,
  check: IconCheck,
  copy: IconCopy,
  refresh: IconRefresh,
  download: IconDownload,

  // Commerce
  cart: IconShoppingCart,
  package: IconPackage,
  creditCard: IconCreditCard,
  wallet: IconWallet,
  gift: IconGift,
  tag: IconTag,
  truck: IconTruck,
  heart: IconHeart,

  // Account
  user: IconUser,
  bell: IconBell,
  lock: IconLock,
  mail: IconMail,
  logout: IconLogout,
  eye: IconEye,
  eyeOff: IconEyeOff,

  // Media
  camera: IconCamera,
  image: IconPhoto,
  play: IconPlayerPlay,
  pause: IconPlayerPause,

  // Communication
  phone: IconPhone,
  message: IconMessageCircle,
  share: IconShare,

  // Status
  info: IconInfoCircle,
  alert: IconAlertCircle,
  star: IconStar,
  settings: IconSettings,
  minus: IconMinus,
  bookmark: IconBookmark,

  // Time & filtering
  calendar: IconCalendar,
  clock: IconClock,
  filter: IconFilter,
  upload: IconUpload,
  history: IconHistory,
  sortAsc: IconArrowsSort,

  // Files & organization
  folder: IconFolder,
  file: IconFileText,
  clipboard: IconClipboard,
  clipboardCheck: IconClipboardCheck,
  layoutGrid: IconLayoutGrid,
  list: IconList,

  // Links & location
  link: IconLink,
  externalLink: IconExternalLink,
  globe: IconWorld,
  mapPin: IconMapPin,
  building: IconBuilding,
  briefcase: IconBriefcase,

  // People & security
  users: IconUsers,
  userPlus: IconUserPlus,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  key: IconKey,

  // Infra
  wifi: IconWifi,
  database: IconDatabase,
  server: IconServer,
  cloud: IconCloud,
  printer: IconPrinter,
  qrCode: IconQrcode,
  barcode: IconBarcode,

  // Feedback & data
  bolt: IconBolt,
  flag: IconFlag,
  thumbUp: IconThumbUp,
  thumbDown: IconThumbDown,
  sun: IconSun,
  moon: IconMoon,
  chartBar: IconChartBar,
  chartPie: IconChartPie,
  trendingUp: IconTrendingUp,
  arrowLeft: IconArrowLeft,
} as const;

export type IconName = keyof typeof icons;

/**
 * Solid ("Filled") counterparts for a subset of icons — not every outline
 * icon has an official filled twin, so `solid` falls back to the outline
 * glyph when one isn't mapped here.
 */
const solidIcons: Partial<Record<IconName, typeof icons[IconName]>> = {
  home: IconHomeFilled,
  search: IconSearchFilled,
  menu: IconMenu2Filled,
  chevronRight: IconChevronRightFilled,
  trash: IconTrashFilled,
  edit: IconEditFilled,
  close: IconXFilled,
  copy: IconCopyFilled,
  download: IconDownloadFilled,
  cart: IconShoppingCartFilled,
  creditCard: IconCreditCardFilled,
  gift: IconGiftFilled,
  tag: IconTagFilled,
  truck: IconTruckFilled,
  heart: IconHeartFilled,
  user: IconUserFilled,
  bell: IconBellFilled,
  lock: IconLockFilled,
  mail: IconMailFilled,
  eye: IconEyeFilled,
  camera: IconCameraFilled,
  image: IconPhotoFilled,
  play: IconPlayerPlayFilled,
  pause: IconPlayerPauseFilled,
  phone: IconPhoneFilled,
  message: IconMessageCircleFilled,
  info: IconInfoCircleFilled,
  alert: IconAlertCircleFilled,
  star: IconStarFilled,
  settings: IconSettingsFilled,
  bookmark: IconBookmarkFilled,
  calendar: IconCalendarFilled,
  clock: IconClockFilled,
  filter: IconFilterFilled,
  folder: IconFolderFilled,
  file: IconFileTextFilled,
  link: IconLinkFilled,
  externalLink: IconExternalLinkFilled,
  globe: IconWorldFilled,
  mapPin: IconMapPinFilled,
  briefcase: IconBriefcaseFilled,
  shield: IconShieldFilled,
  shieldCheck: IconShieldCheckFilled,
  key: IconKeyFilled,
  database: IconDatabaseFilled,
  cloud: IconCloudFilled,
  clipboard: IconClipboardFilled,
  clipboardCheck: IconClipboardCheckFilled,
  bolt: IconBoltFilled,
  flag: IconFlagFilled,
  thumbUp: IconThumbUpFilled,
  thumbDown: IconThumbDownFilled,
  sun: IconSunFilled,
  moon: IconMoonFilled,
  layoutGrid: IconLayoutGridFilled,
  list: IconListFilled,
  chartPie: IconChartPieFilled,
};

export interface IconComponentProps extends Omit<IconProps, "ref"> {
  name: IconName;
  /** Render the solid/filled glyph instead of the outline one, when available. */
  solid?: boolean;
}

// Tabler icons draw on a 24-unit viewBox and scale it to `size` px, so the
// rendered stroke is `stroke * (size / 24)` — below ~14px that can dip
// under 1 physical pixel and disappear. Floor it so every icon, at any
// size, keeps at least a 1px stroke.
const VIEWBOX = 24;

export function Icon({ name, solid, size = 20, stroke = 1.75, ...props }: IconComponentProps) {
  const Component = (solid && solidIcons[name]) || icons[name];
  const numericSize = typeof size === "number" ? size : Number(size);
  const numericStroke = typeof stroke === "number" ? stroke : Number(stroke);
  const minStroke = Number.isFinite(numericSize) && numericSize > 0 ? VIEWBOX / numericSize : 0;
  const effectiveStroke = Math.max(numericStroke, minStroke);
  return <Component size={size} stroke={effectiveStroke} {...props} />;
}
